### PR TITLE
feature/fix: allow whitespace separated string values

### PR DESCRIPTION
**Pull request by NiclasThobaben**
When an argument in form of `--argument="My whitespace string"` was
passed, only the first character before the whitespace were parsed. So the result would be:
`````js
{ argument: 'My' }
`````
Because the arguments are aready split when passed to argv from the commandline we can
split the value with `/.*/` from the key.

Nice simple tool btw!

### CODE REVIEW

**Comment by eveningkid** [comment]
Hi Niclas,

Thank you for contributing to the repo :)

I tried your suggestion and by fixing A, turns out it broke B!

Here you can find playgrounds to see how both regexes compare:
- [Current implementation](https://regex101.com/r/BqVTBg/1)
- [Your suggestion](https://regex101.com/r/rq7bo7/1)

As you can see there are extra spaces that are matched with your code. We could use `string.trim()` but there should be a way to not match spaces if there's any before the value.

If you want to give it a try!

PS: you left a `console.log` in your code that needs to be removed

**Comment by NiclasThobaben** [comment]
I tried fixing it in the [regex](https://regex101.com/r/Jhu5Mn/1/), which seemed promising, but when i included it in the code it didn't work.

Turns out the quotes will be stripped by node, so instead of `--a="My test"`  it becomes `--a=My test` and the regex is not working.

But if i'm not mistaken we just use the regex on the already split arguments from `argv`, so maybe this is not a problem after all, because it doesn't affect the already matched arguments? A space between = and "..." would probably require a whole other mechanism anyway.

At least my own tests yield the expected result with my current regex:

```bash
// test.js
const parse = require('./parse')
console.log(parse(process.argv))

$ node test.js careful -dangerous --tomatoes=3 --tonight --key=ek== -quotes1="my test==" -quotes2='my test==' quotes3="my test=="

{ 
  careful: true,
  dangerous: true,
  tomatoes: 3,
  tonight: true,
  key: 'ek==',
  quotes1: 'my test==',
  quotes2: 'my test==',
  quotes3: 'my test==',
}
``` 
What do you think?

PS.: sorry for the `console.log`, I removed it :)

**Comment by eveningkid** [comment]
Just to make sure we understand each other: the following is what I'm talking about.

image

By using your regex, it catches spaces we don't need. And while this could be fixed with `argValue.trim()`, I'm sure it can done in the regex directly.

Now, from what you sent in your last message, I see it working but it wouldn't with:

```
--branch test
> ["--branch", " test"] (with the extra space)
> ["--branch", "test"] (expected)
```

**Comment by NiclasThobaben** [comment]
Ah my mistake! Thanks for clearing that up!
[This](https://regex101.com/r/yN2Ev3/1/) should fix it.

**Comment by eveningkid** [comment]
Great, almost there (I know it's annoying but haha):

1) The regex should be: `([^=\s]+)=?\s*(.*)`
I've replaced `\s?` with `\s*` since you can have multiple spaces `--branch    test`
2) Please remove the empty line on line 19
3) Make sure to update the minified file which is the one used by npm

I promise, it should be ready to merge after that :)

**Comment by NiclasThobaben** [comment]
Alright, hope its all correct now. 
I had a wrong email address configured, thats why i had to amend the commits.

This was my first contribution on an open source project, so I am still learning :)

**Comment by eveningkid** [comment]
That's perfect now Niclas, thanks a lot!
I'll merge this PR and make the change available in `1.3.0`.

Really happy this happened to be your first contribution.
I wish you the best for what's to come!

Have a great day :)

**Pull request merged**
